### PR TITLE
EnteringState extension method

### PR DESCRIPTION
**Pull request by ursenzler**
Add an extension method that is called before a state is entered.

### CODE REVIEW

**Comment by hpradogu** [comment]
Hi Urs,

Wow! Thank you so much for putting this together. It is VERY much appreciated.

I will pull this shortly and test it out, and confirm everything's working.

Happy Friday!
-Hector

**Comment by hpradogu** [comment]
Hi Urs!

Sorry for the delay. I've finally got my environment working, and it looks like the EnteringState worked exactly as I needed it to!

So, thank you very much for your help on this!! I really appreciate it.

Best,
Hector

**Comment by hpradogu** [comment]
Hi Urs!

I know it's been sometime now. I want to say thank you again for doing this!

We've had our project on pause and are now coming back to it. We were trying to update to the latest and greatest (seeing as how you've merged this into master, but noticed a TON of new dependencies. Is there a flag or a way to comment out pulling all of the new dependencies? 

We strive to keep our project as compact as possible. If there are some features in there that require it, what would those be, and would we be able to disable them (assuming we won't need them in our project), etc.?

Additionally, what would be the easiest way of fixing the issues based on the screenshot below? Seems like there's some breaking changes in the API, and we're hoping to be able to fix with the least amount of code change as possible, if possible :)
Screen Shot 2021-06-04 at 09 47 07

Thanks!!
Hector

**Comment by ursenzler** [comment]
Hi Hector, nice to hear from you.

I don't know which dependencies you mean. There are none.

The two methods in the screenshot do not exist anymore. There still is the `EnteringInitialState` method that gets called at the same time.

Happy coding, Urs

**Comment by hpradogu** [comment]
Hi Urs!

Thanks for the quick response! Please see this screenshot Screen Shot 2021-06-09 at 09 22 31 for the dependencies I'm referring to when trying to upgrade. Any idea why that may be?

Got it. Those 2 methods are no longer valid due to the builder syntax you've created, per the docs, right?

Thanks!
Hector

**Comment by ursenzler** [comment]
Oops, your message got lost on my to-do list.
I'm not sure, but these are all .NET dependencies that are probably referenced anyway?!?! They are not explicitly referenced by the state machine.

And yes, the 2 methods are removed because the initialization is different now.

**Comment by hpradogu** [comment]
Hi Urs,

Not a problem. Thanks for the response!

It only seems to happen when upgrading from Appccelerate 5.0.0 to 5.1.0. If there's nothing to do, then we'll just have to deal with it :)

Got it! Ok, thank you!

I'll give it a go and see how I can update my current code base to the latest version of building up a state machine.

Thanks so much!
Hector

**Pull request merged**
